In [ ]:
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
from datetime import datetime
import warnings
warnings.filterwarnings('ignore')
!pip install catboost
from sklearn.metrics import mean_absolute_percentage_error
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from pandas import DataFrame

Collecting catboost
  Downloading catboost-1.0.4-cp37-none-manylinux1_x86_64.whl (76.1 MB)
     |████████████████████████████████| 76.1 MB 42 kB/s
Requirement already satisfied: plotly in /usr/local/lib/python3.7/dist-packages (from catboost) (5.5.0)
Requirement already satisfied: pandas>=0.24.0 in /usr/local/lib/python3.7/dist-packages (from catboost) (1.3.5)
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from catboost) (1.15.0)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.7/dist-packages (from catboost) (3.2.2)
Requirement already satisfied: graphviz in /usr/local/lib/python3.7/dist-packages (from catboost) (0.10.1)
Requirement already satisfied: numpy>=1.16.0 in /usr/local/lib/python3.7/dist-packages (from catboost) (1.21.5)
Requirement already satisfied: scipy in /usr/local/lib/python3.7/dist-packages (from catboost) (1.4.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.0->catboost) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.0->catboost) (2018.9)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib->catboost) (1.3.2)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib->catboost) (3.0.7)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.7/dist-packages (from matplotlib->catboost) (0.11.0)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.7/dist-packages (from plotly->catboost) (8.0.1)
Installing collected packages: catboost
Successfully installed catboost-1.0.4

In [ ]:
def mape(actual, pred): 
    actual, pred = np.array(actual), np.array(pred)
    mape_arr=(np.abs(actual - pred) / actual)*100
    return (mape_arr,np.mean( (np.abs(actual - pred) / actual) * 100))

In [ ]:
df1=pd.read_csv('stackedSouth_test.csv')

df1=df1.drop(['Unnamed: 0'],axis=1)

df1=df1.drop(['SKU_id'],axis=1)
df1_copy=df1.copy(deep=True)
trans = StandardScaler()
data = trans.fit_transform(df1)
# convert the array back to a dataframe
df1 = pd.DataFrame(data, columns=[
  '1', '2', '3', '4','5','6','7','8','9','10','11'])
df1

,1,2,3,4,5,6,7,8,9,10,11
0,-0.415230,-0.434420,0.244351,4.466770,-0.442778,-0.460985,-0.376034,-0.281929,-0.288084,-0.169729,-0.316412
1,-0.466674,-0.407735,-0.317968,-0.509545,-0.435249,-0.455737,-0.413561,-0.326515,-0.286968,-0.408855,-0.074846
2,-0.452384,-0.473235,-0.437842,-0.499020,-0.478541,-0.467982,-0.419487,-0.386535,-0.352785,-0.429268,-0.347582
3,-0.312342,-0.228216,8.374003,1.477613,-0.295962,-0.438244,-0.054094,-0.059000,-0.199956,0.057732,0.034249
4,-0.106565,0.344304,4.082506,1.006084,-0.171733,-0.266812,-0.144948,0.211945,0.541882,1.623714,-0.152770
...,...,...,...,...,...,...,...,...,...,...,...
281,-0.200879,0.924103,-0.106553,0.427198,-0.102089,-0.258065,0.022935,0.093621,-0.361710,-0.475927,0.587514
282,-0.469532,-0.487791,-0.450919,-0.486389,-0.256435,-0.478478,-0.383935,-0.396824,-0.254617,-0.353448,-0.394337
283,-0.458100,-0.478087,-0.442201,-0.503230,-0.482306,-0.471481,-0.407636,-0.389964,-0.355016,-0.458430,-0.363167
284,-0.469532,-0.487791,-0.450919,-0.494810,-0.482306,-0.474979,-0.378010,-0.376246,-0.350554,-0.470094,-0.394337
285,-0.452384,-0.473235,-0.437842,-0.499020,-0.478541,-0.100628,0.386352,0.148496,0.503953,0.597223,-0.207318

In [ ]:
df2=pd.read_csv('stackedSouth_train.csv')
df2=df2.drop(['Unnamed: 0'],axis=1)
df2=df2.drop(['0'],axis=1)
df2=df2.drop(['12'],axis=1)
data1 = trans.fit_transform(df2)
# convert the array back to a dataframe
df2 = pd.DataFrame(data1, columns=[
  '1', '2', '3', '4','5','6','7','8','9','10','11'])
#df1.rename(columns = {'0':'1','1':'2','2':'3','3':'4','4':'5','5':'6','6':'7','7':'8','8':'9','9':'10','10':'11'}, inplace = True)
df2

,1,2,3,4,5,6,7,8,9,10,11
0,0.233741,-0.396877,-0.375507,-0.328471,-0.283646,-0.309034,-0.243658,-0.302654,0.011670,-0.329985,-0.293254
1,-0.298788,-0.343557,-0.448722,-0.404540,-0.428392,-0.309034,-0.274672,-0.424484,-0.168795,-0.321561,-0.211408
2,-0.435091,-0.408102,-0.458706,-0.422289,-0.446168,-0.412815,-0.416821,-0.422048,-0.366448,-0.447927,-0.410442
3,-0.311468,-0.287431,0.236838,0.056945,-0.265870,0.009549,-0.176461,-0.229556,0.140575,-0.095788,-0.185366
4,0.290797,-0.093796,-0.075990,0.127943,-0.055099,-0.077338,-0.305687,-0.141838,-0.106921,-0.016598,0.181080
...,...,...,...,...,...,...,...,...,...,...,...
567,-0.460449,-0.430553,-0.485330,-0.442575,-0.466483,-0.190772,-0.189383,-0.285598,-0.332074,-0.461406,-0.432764
568,-0.390713,-0.391264,-0.398803,-0.305650,-0.319197,-0.417642,-0.421990,-0.378189,-0.376761,-0.390641,-0.399281
569,-0.441430,-0.413715,-0.438738,-0.427361,-0.430931,-0.417642,-0.421990,-0.426921,-0.369886,-0.437817,-0.421603
570,-0.441430,-0.402490,-0.472018,-0.437503,-0.430931,-0.427296,-0.432328,-0.417175,-0.369886,-0.447927,-0.421603
571,-0.435091,-0.408102,-0.418771,-0.422289,-0.446168,-0.412815,-0.416821,-0.422048,-0.273637,-0.048611,-0.250471

In [ ]:
x_train=df2.drop(['11'],axis=1)
x_train

,1,2,3,4,5,6,7,8,9,10
0,0.233741,-0.396877,-0.375507,-0.328471,-0.283646,-0.309034,-0.243658,-0.302654,0.011670,-0.329985
1,-0.298788,-0.343557,-0.448722,-0.404540,-0.428392,-0.309034,-0.274672,-0.424484,-0.168795,-0.321561
2,-0.435091,-0.408102,-0.458706,-0.422289,-0.446168,-0.412815,-0.416821,-0.422048,-0.366448,-0.447927
3,-0.311468,-0.287431,0.236838,0.056945,-0.265870,0.009549,-0.176461,-0.229556,0.140575,-0.095788
4,0.290797,-0.093796,-0.075990,0.127943,-0.055099,-0.077338,-0.305687,-0.141838,-0.106921,-0.016598
...,...,...,...,...,...,...,...,...,...,...
567,-0.460449,-0.430553,-0.485330,-0.442575,-0.466483,-0.190772,-0.189383,-0.285598,-0.332074,-0.461406
568,-0.390713,-0.391264,-0.398803,-0.305650,-0.319197,-0.417642,-0.421990,-0.378189,-0.376761,-0.390641
569,-0.441430,-0.413715,-0.438738,-0.427361,-0.430931,-0.417642,-0.421990,-0.426921,-0.369886,-0.437817
570,-0.441430,-0.402490,-0.472018,-0.437503,-0.430931,-0.427296,-0.432328,-0.417175,-0.369886,-0.447927
571,-0.435091,-0.408102,-0.418771,-0.422289,-0.446168,-0.412815,-0.416821,-0.422048,-0.273637,-0.048611

In [ ]:
y_train=df2.iloc[:,10]
y_train

0     -0.293254
1     -0.211408
2     -0.410442
3     -0.185366
4      0.181080
         ...
567   -0.432764
568   -0.399281
569   -0.421603
570   -0.421603
571   -0.250471
Name: 11, Length: 572, dtype: float64

In [ ]:
x_test=df1.drop(['11'],axis=1)
x_test

,1,2,3,4,5,6,7,8,9,10
0,-0.415230,-0.434420,0.244351,4.466770,-0.442778,-0.460985,-0.376034,-0.281929,-0.288084,-0.169729
1,-0.466674,-0.407735,-0.317968,-0.509545,-0.435249,-0.455737,-0.413561,-0.326515,-0.286968,-0.408855
2,-0.452384,-0.473235,-0.437842,-0.499020,-0.478541,-0.467982,-0.419487,-0.386535,-0.352785,-0.429268
3,-0.312342,-0.228216,8.374003,1.477613,-0.295962,-0.438244,-0.054094,-0.059000,-0.199956,0.057732
4,-0.106565,0.344304,4.082506,1.006084,-0.171733,-0.266812,-0.144948,0.211945,0.541882,1.623714
...,...,...,...,...,...,...,...,...,...,...
281,-0.200879,0.924103,-0.106553,0.427198,-0.102089,-0.258065,0.022935,0.093621,-0.361710,-0.475927
282,-0.469532,-0.487791,-0.450919,-0.486389,-0.256435,-0.478478,-0.383935,-0.396824,-0.254617,-0.353448
283,-0.458100,-0.478087,-0.442201,-0.503230,-0.482306,-0.471481,-0.407636,-0.389964,-0.355016,-0.458430
284,-0.469532,-0.487791,-0.450919,-0.494810,-0.482306,-0.474979,-0.378010,-0.376246,-0.350554,-0.470094
285,-0.452384,-0.473235,-0.437842,-0.499020,-0.478541,-0.100628,0.386352,0.148496,0.503953,0.597223

In [ ]:
y_test=df1_copy.iloc[:,10]
y_test

0       19
1       50
2       15
3       64
4       40
      ...
281    135
282      9
283     13
284      9
285     33
Name: May_21, Length: 286, dtype: int64

In [ ]:
from catboost import CatBoostRegressor
model=CatBoostRegressor(iterations=18, depth=3, learning_rate=0.1, loss_function='MAPE')
model.fit(x_train, y_train,eval_set=(x_test, y_test),plot=True)

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

0:	learn: 0.2581919	test: 1.0350608	best: 1.0350608 (0)	total: 47.1ms	remaining: 801ms
1:	learn: 0.2440090	test: 1.0340263	best: 1.0340263 (1)	total: 48ms	remaining: 384ms
2:	learn: 0.2303122	test: 1.0330983	best: 1.0330983 (2)	total: 48.9ms	remaining: 244ms
3:	learn: 0.2169820	test: 1.0324214	best: 1.0324214 (3)	total: 49.7ms	remaining: 174ms
4:	learn: 0.2057788	test: 1.0314183	best: 1.0314183 (4)	total: 50.5ms	remaining: 131ms
5:	learn: 0.1971438	test: 1.0307866	best: 1.0307866 (5)	total: 51.2ms	remaining: 102ms
6:	learn: 0.1901114	test: 1.0301401	best: 1.0301401 (6)	total: 52.1ms	remaining: 81.9ms
7:	learn: 0.1834079	test: 1.0295493	best: 1.0295493 (7)	total: 52.9ms	remaining: 66.1ms
8:	learn: 0.1747325	test: 1.0292543	best: 1.0292543 (8)	total: 53.8ms	remaining: 53.8ms
9:	learn: 0.1688117	test: 1.0291733	best: 1.0291733 (9)	total: 54.9ms	remaining: 43.9ms
10:	learn: 0.1630613	test: 1.0289932	best: 1.0289932 (10)	total: 55.9ms	remaining: 35.6ms
11:	learn: 0.1556814	test: 1.0287659	best: 1.0287659 (11)	total: 57ms	remaining: 28.5ms
12:	learn: 0.1502487	test: 1.0285723	best: 1.0285723 (12)	total: 58.1ms	remaining: 22.3ms
13:	learn: 0.1473255	test: 1.0283393	best: 1.0283393 (13)	total: 59ms	remaining: 16.9ms
14:	learn: 0.1447421	test: 1.0282062	best: 1.0282062 (14)	total: 60ms	remaining: 12ms
15:	learn: 0.1411029	test: 1.0279052	best: 1.0279052 (15)	total: 61ms	remaining: 7.62ms
16:	learn: 0.1391926	test: 1.0276915	best: 1.0276915 (16)	total: 61.9ms	remaining: 3.64ms
17:	learn: 0.1375811	test: 1.0275757	best: 1.0275757 (17)	total: 62.9ms	remaining: 0us

bestTest = 1.027575726
bestIteration = 17

In [ ]:
k=model.predict(x_test)
k = pd.DataFrame(k, columns=[
  '10'])
print(k)
d = pd.DataFrame(np.zeros((286, 10)))
k=pd.concat([d,k], axis=1)
k=trans.inverse_transform(k)
k=k[:,10]
t=np.floor(k)
t

           10
0    0.164573
1   -0.355242
2   -0.381287
3    0.330540
4    0.324598
..        ...
281 -0.428716
282 -0.365159
283 -0.427934
284 -0.427934
285 -0.092641

[286 rows x 1 columns]

array([328.,  48.,  34., 417., 414.,  10., 607., 607.,  69., 349., 312.,
       607., 323.,  55.,  10.,  14.,  42.,  11., 177.,  99.,  14., 173.,
        69., 189., 259.,  60., 187., 457.,  65., 299., 249.,  11.,  13.,
        83., 364.,  17.,  77., 190., 242., 404., 544., 272.,  97., 207.,
        55.,  73.,  11., 212., 432.,  12., 366., 220.,  81., 267., 432.,
        56.,  89.,  11.,   8., 122., 214., 305., 125.,  48.,  56., 103.,
       206.,  90., 274., 180.,  53.,  17.,  20.,  13., 126.,  17.,  42.,
        11.,  13.,  19.,  38., 178.,  61., 471., 607., 147., 300.,  56.,
       188.,  10.,  11., 471., 254., 115.,  65.,  60.,  11.,  17.,  11.,
        56., 291., 188., 264.,   9., 192.,  12., 172., 233., 210., 195.,
       380., 285., 171., 296., 159., 607., 147., 548., 108., 607.,  38.,
       505., 276., 373., 607., 259.,  13.,  11.,  10., 319.,  39., 125.,
       116., 432., 165., 218., 126.,  65.,  17.,  48.,  47.,  15.,  13.,
       269.,  98., 212., 131., 172., 387., 124., 404., 326.,  57., 254.,
         9., 264.,  55.,  10.,   9.,  10.,  39., 267., 195., 185.,   9.,
        65.,  43.,  63.,  56., 115.,  60.,  55.,  65., 505., 137.,  48.,
       273.,  50., 242.,  69., 173., 291., 607., 850., 339., 350., 538.,
       106., 607., 220.,  12., 126.,  99.,  13., 153.,  56., 275., 235.,
       232., 112., 198.,  12., 335., 607., 505.,  13.,  77.,  42., 180.,
        65.,  34.,  82.,  65.,  47.,  51.,  42.,  86.,  56.,  52.,  47.,
        12.,  47.,  22.,   9., 173.,  13.,  34.,  40.,   9.,  81.,  81.,
         8.,  52.,   9.,   9.,  43., 126.,  11.,  56.,  53.,  82., 112.,
       129.,  38.,  60.,  40.,  78.,  72.,  60.,  30.,  64.,  12.,  30.,
       112.,   9.,  11.,  48.,  43.,   9.,  42.,   9.,  51.,   9., 522.,
        50., 423.,  10.,  42., 187.,  10.,   8., 134.,  34.,  81.,  56.,
       258.,  80., 159., 254.,  13.,  12.,   9.,  43.,   9.,   9., 189.])

In [ ]:
a,b=mape(y_test,t)
b

549.8188982815508

In [ ]:
mapef=0
c=0
bad_examples_north=[]

In [ ]:
for i in range(len(y_test)):
  if np.abs((y_test.iloc[i]-t[i])/(y_test.iloc[i]))<0.9:
    mapef=mapef+np.abs((y_test.iloc[i]-t[i])/(y_test.iloc[i]))
    c=c+1
  else:
    bad_examples_north.append(i)  
mape_final=mapef/c  
print(mape_final)

0.36459184293177066

In [ ]:
len(bad_examples_north)

203