In [ ]:
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
from datetime import datetime
import warnings
warnings.filterwarnings('ignore')
!pip install catboost
from sklearn.metrics import mean_absolute_percentage_error
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from pandas import DataFrame

Collecting catboost
  Downloading catboost-1.0.4-cp37-none-manylinux1_x86_64.whl (76.1 MB)
     |████████████████████████████████| 76.1 MB 64 kB/s
Requirement already satisfied: scipy in /usr/local/lib/python3.7/dist-packages (from catboost) (1.4.1)
Requirement already satisfied: graphviz in /usr/local/lib/python3.7/dist-packages (from catboost) (0.10.1)
Requirement already satisfied: pandas>=0.24.0 in /usr/local/lib/python3.7/dist-packages (from catboost) (1.3.5)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.7/dist-packages (from catboost) (3.2.2)
Requirement already satisfied: numpy>=1.16.0 in /usr/local/lib/python3.7/dist-packages (from catboost) (1.21.5)
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from catboost) (1.15.0)
Requirement already satisfied: plotly in /usr/local/lib/python3.7/dist-packages (from catboost) (5.5.0)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.0->catboost) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.0->catboost) (2018.9)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib->catboost) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.7/dist-packages (from matplotlib->catboost) (0.11.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib->catboost) (3.0.7)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.7/dist-packages (from plotly->catboost) (8.0.1)
Installing collected packages: catboost
Successfully installed catboost-1.0.4

In [ ]:
def mape(actual, pred): 
    actual, pred = np.array(actual), np.array(pred)
    mape_arr=(np.abs(actual - pred) / actual)*100
    return (mape_arr,np.mean( (np.abs(actual - pred) / actual) * 100))

In [ ]:
df1=pd.read_csv('stackedSouth_test.csv')

df1=df1.drop(['Unnamed: 0'],axis=1)

df1=df1.drop(['SKU_id'],axis=1)
df1_copy=df1.copy(deep=True)
trans = MinMaxScaler()
data = trans.fit_transform(df1)
# convert the array back to a dataframe
df1 = pd.DataFrame(data, columns=[
  '1', '2', '3', '4','5','6','7','8','9','10','11'])
df1

,1,2,3,4,5,6,7,8,9,10,11
0,0.008780,0.007213,0.080601,0.657159,0.006703,0.003130,0.007884,0.009932,0.007126,0.041667,0.015789
1,0.002927,0.009858,0.017008,0.002492,0.007516,0.003652,0.003723,0.006442,0.007225,0.010886,0.042982
2,0.004553,0.003366,0.003451,0.003877,0.002844,0.002434,0.003066,0.001745,0.001386,0.008258,0.012281
3,0.020488,0.027651,1.000000,0.263916,0.022547,0.005390,0.043583,0.027379,0.014945,0.070946,0.055263
4,0.043902,0.084395,0.514666,0.201883,0.035954,0.022431,0.033509,0.048584,0.080760,0.272523,0.034211
...,...,...,...,...,...,...,...,...,...,...,...
281,0.033171,0.141861,0.040917,0.125727,0.043469,0.023300,0.052124,0.039324,0.000594,0.002252,0.117544
282,0.002602,0.001924,0.001972,0.005539,0.026813,0.001391,0.007008,0.000939,0.010095,0.018018,0.007018
283,0.003902,0.002885,0.002958,0.003323,0.002438,0.002087,0.004380,0.001476,0.001188,0.004505,0.010526
284,0.002602,0.001924,0.001972,0.004431,0.002438,0.001739,0.007665,0.002550,0.001584,0.003003,0.007018
285,0.004553,0.003366,0.003451,0.003877,0.002844,0.038950,0.092422,0.043618,0.077395,0.140390,0.028070

In [ ]:
df2=pd.read_csv('stackedSouth_train.csv')
df2=df2.drop(['Unnamed: 0'],axis=1)
df2=df2.drop(['0'],axis=1)
df2=df2.drop(['12'],axis=1)

data1 = trans.fit_transform(df2)
# convert the array back to a dataframe
df2 = pd.DataFrame(data1, columns=[
  '1', '2', '3', '4','5','6','7','8','9','10','11',])
#df1.rename(columns = {'0':'1','1':'2','2':'3','3':'4','4':'5','5':'6','6':'7','7':'8','8':'9','9':'10','10':'11'}, inplace = True)
df2

,1,2,3,4,5,6,7,8,9,10,11
0,0.076557,0.005075,0.014156,0.013347,0.024968,0.012525,0.020732,0.014820,0.029912,0.017603,0.012786
1,0.019394,0.010431,0.006171,0.005496,0.006722,0.012525,0.017661,0.003058,0.016490,0.018650,0.019732
2,0.004764,0.003947,0.005082,0.003664,0.004481,0.003076,0.003583,0.003293,0.001790,0.002934,0.002841
3,0.018033,0.016070,0.080944,0.053127,0.027209,0.041529,0.027387,0.021877,0.039499,0.046731,0.021942
4,0.082681,0.035523,0.046824,0.060455,0.053777,0.033619,0.014589,0.030346,0.021092,0.056580,0.053039
...,...,...,...,...,...,...,...,...,...,...,...
567,0.002042,0.001692,0.002178,0.001570,0.001921,0.023292,0.026107,0.016467,0.004346,0.001257,0.000947
568,0.009527,0.005639,0.011615,0.015703,0.020487,0.002637,0.003071,0.007528,0.001023,0.010059,0.003788
569,0.004083,0.003383,0.007260,0.003141,0.006402,0.002637,0.003071,0.002823,0.001534,0.004191,0.001894
570,0.004083,0.004511,0.003630,0.002094,0.006402,0.001758,0.002048,0.003764,0.001534,0.002934,0.001894
571,0.004764,0.003947,0.009437,0.003664,0.004481,0.003076,0.003583,0.003293,0.008692,0.052598,0.016417

In [ ]:
x_train=df2.drop(['11'],axis=1)
x_train

,1,2,3,4,5,6,7,8,9,10
0,0.076557,0.005075,0.014156,0.013347,0.024968,0.012525,0.020732,0.014820,0.029912,0.017603
1,0.019394,0.010431,0.006171,0.005496,0.006722,0.012525,0.017661,0.003058,0.016490,0.018650
2,0.004764,0.003947,0.005082,0.003664,0.004481,0.003076,0.003583,0.003293,0.001790,0.002934
3,0.018033,0.016070,0.080944,0.053127,0.027209,0.041529,0.027387,0.021877,0.039499,0.046731
4,0.082681,0.035523,0.046824,0.060455,0.053777,0.033619,0.014589,0.030346,0.021092,0.056580
...,...,...,...,...,...,...,...,...,...,...
567,0.002042,0.001692,0.002178,0.001570,0.001921,0.023292,0.026107,0.016467,0.004346,0.001257
568,0.009527,0.005639,0.011615,0.015703,0.020487,0.002637,0.003071,0.007528,0.001023,0.010059
569,0.004083,0.003383,0.007260,0.003141,0.006402,0.002637,0.003071,0.002823,0.001534,0.004191
570,0.004083,0.004511,0.003630,0.002094,0.006402,0.001758,0.002048,0.003764,0.001534,0.002934
571,0.004764,0.003947,0.009437,0.003664,0.004481,0.003076,0.003583,0.003293,0.008692,0.052598

In [ ]:
y_train=df2.iloc[:,10]
y_train

0      0.012786
1      0.019732
2      0.002841
3      0.021942
4      0.053039
         ...
567    0.000947
568    0.003788
569    0.001894
570    0.001894
571    0.016417
Name: 11, Length: 572, dtype: float64

In [ ]:
x_test=df1.drop(['11'],axis=1)
x_test

,1,2,3,4,5,6,7,8,9,10
0,0.008780,0.007213,0.080601,0.657159,0.006703,0.003130,0.007884,0.009932,0.007126,0.041667
1,0.002927,0.009858,0.017008,0.002492,0.007516,0.003652,0.003723,0.006442,0.007225,0.010886
2,0.004553,0.003366,0.003451,0.003877,0.002844,0.002434,0.003066,0.001745,0.001386,0.008258
3,0.020488,0.027651,1.000000,0.263916,0.022547,0.005390,0.043583,0.027379,0.014945,0.070946
4,0.043902,0.084395,0.514666,0.201883,0.035954,0.022431,0.033509,0.048584,0.080760,0.272523
...,...,...,...,...,...,...,...,...,...,...
281,0.033171,0.141861,0.040917,0.125727,0.043469,0.023300,0.052124,0.039324,0.000594,0.002252
282,0.002602,0.001924,0.001972,0.005539,0.026813,0.001391,0.007008,0.000939,0.010095,0.018018
283,0.003902,0.002885,0.002958,0.003323,0.002438,0.002087,0.004380,0.001476,0.001188,0.004505
284,0.002602,0.001924,0.001972,0.004431,0.002438,0.001739,0.007665,0.002550,0.001584,0.003003
285,0.004553,0.003366,0.003451,0.003877,0.002844,0.038950,0.092422,0.043618,0.077395,0.140390

In [ ]:
y_test=df1_copy.iloc[:,10]
y_test

0       19
1       50
2       15
3       64
4       40
      ...
281    135
282      9
283     13
284      9
285     33
Name: May_21, Length: 286, dtype: int64

In [ ]:
from catboost import CatBoostRegressor
model=CatBoostRegressor(iterations=18, depth=3, learning_rate=0.1, loss_function='MAPE')
model.fit(x_train, y_train,eval_set=(x_test, y_test),plot=True)

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

0:	learn: 0.0338863	test: 0.9995597	best: 0.9995597 (0)	total: 1.66ms	remaining: 28.3ms
1:	learn: 0.0321671	test: 0.9994460	best: 0.9994460 (1)	total: 4.98ms	remaining: 39.9ms
2:	learn: 0.0303142	test: 0.9993300	best: 0.9993300 (2)	total: 7.22ms	remaining: 36.1ms
3:	learn: 0.0286642	test: 0.9992435	best: 0.9992435 (3)	total: 8.13ms	remaining: 28.5ms
4:	learn: 0.0274697	test: 0.9991599	best: 0.9991599 (4)	total: 9.04ms	remaining: 23.5ms
5:	learn: 0.0267519	test: 0.9990877	best: 0.9990877 (5)	total: 10ms	remaining: 20.1ms
6:	learn: 0.0256684	test: 0.9990492	best: 0.9990492 (6)	total: 11ms	remaining: 17.3ms
7:	learn: 0.0250186	test: 0.9989846	best: 0.9989846 (7)	total: 12ms	remaining: 15ms
8:	learn: 0.0244862	test: 0.9989460	best: 0.9989460 (8)	total: 12.9ms	remaining: 12.9ms
9:	learn: 0.0237492	test: 0.9989281	best: 0.9989281 (9)	total: 13.9ms	remaining: 11.2ms
10:	learn: 0.0231712	test: 0.9989189	best: 0.9989189 (10)	total: 15ms	remaining: 9.55ms
11:	learn: 0.0222531	test: 0.9988897	best: 0.9988897 (11)	total: 15.9ms	remaining: 7.97ms
12:	learn: 0.0213506	test: 0.9988652	best: 0.9988652 (12)	total: 16.9ms	remaining: 6.5ms
13:	learn: 0.0209163	test: 0.9988148	best: 0.9988148 (13)	total: 17.9ms	remaining: 5.1ms
14:	learn: 0.0201854	test: 0.9988019	best: 0.9988019 (14)	total: 18.8ms	remaining: 3.76ms
15:	learn: 0.0198469	test: 0.9987919	best: 0.9987919 (15)	total: 19.8ms	remaining: 2.47ms
16:	learn: 0.0192928	test: 0.9987868	best: 0.9987868 (16)	total: 20.7ms	remaining: 1.22ms
17:	learn: 0.0187842	test: 0.9987641	best: 0.9987641 (17)	total: 21.7ms	remaining: 0us

bestTest = 0.9987640701
bestIteration = 17

In [ ]:
k=model.predict(x_test)
#print(k)
k = pd.DataFrame(k, columns=[
  '10'])
print(k)
d = pd.DataFrame(np.zeros((286, 10)))
k=pd.concat([d,k], axis=1)
k=trans.inverse_transform(k)
k=k[:,10]
t=np.floor(k)
t.shape

           10
0    0.051606
1    0.008433
2    0.006250
3    0.063523
4    0.097019
..        ...
281  0.014885
282  0.006955
283  0.004279
284  0.001972
285  0.033092

[286 rows x 1 columns]

(286,)

In [ ]:
a,b=mape(y_test,t)
b

691.329828497434

In [ ]:
mapef=0
c=0
bad_examples_north=[]

In [ ]:
for i in range(len(y_test)):
  if np.abs((y_test.iloc[i]-t[i])/(y_test.iloc[i]))<0.9:
    mapef=mapef+np.abs((y_test.iloc[i]-t[i])/(y_test.iloc[i]))
    c=c+1
  else:
    bad_examples_north.append(i)  
mape_final=mapef/c  
print(mape_final)

0.4686942157925562

In [ ]:
len(bad_examples_north)

226